version: 2.1

orbs:
  python: circleci/python@1.5.0

# Define a job to be invoked later in a workflow.
jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
        auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: cimg/postgres:14.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: testuser
          POSTGRES_DB: recommend
          POSTGRES_PASSWORD: ""

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Run tests
          command: cd src && python -m pytest

      - run:
          name: Run coverage
          command: cd src && coverage run -m pytest
      - run:
          name: Create coverage report
          command: cd src && coverage report
      - run:
          name: Create HTML coverage report
          command: cd src && coverage html

# Invoke jobs via workflows
workflows:
  main: #
    jobs:
      - build-and-test
