version: 2.1

orbs:
  python: circleci/python@1.5.0

# Define a job to be invoked later in a workflow.
jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Run tests
          command: cd src && python -m pytest

# Invoke jobs via workflows
workflows:
  main: #
    jobs:
      - build-and-test
